# Site Configuration for Docsie.io
# This file controls build behavior and site settings

# Version Control
# Controls which version of the homepage to use
# Options: "v1" (original index.html), "v2" (index_v2.html), "v3" (index_v3.html)
homepage_version: "v2"

# Pricing page version
# Options: "v1" (pricing/index.html), "v2" (pricing_v2/index.html)
pricing_version: "v2"

# Canonical URL Configuration
# IMPORTANT: This should always be www.docsie.io for SEO
canonical_domain: "https://www.docsie.io"

# Build Settings
verbose_build: true

# Feature Flags
enable_v3_preview: false  # Set to true to enable v3 in development
enable_multilingual: true
enable_blog: true

# Development Settings
dev_port: 8081
auto_reload: true