- id: product-documentation
  category: Solutions
  title: Documentation Produit
  description: Renforcez votre expertise produit avec Docsie. Améliorez la capacité
    de votre entreprise à créer et maintenir une documentation produit complète qui
    favorise l'adoption utilisateur et réduit les coûts de support.
  components:
    hero:
      image: /assets/solutions/product-docs-hero.jpg
      title: Documentation Produit Professionnelle
      description: Créez, gérez et diffusez une documentation produit complète qui
        améliore l'expérience utilisateur et réduit les demandes de support jusqu'à
        65%
      cta:
        text: Réserver une démonstration
        url: /demo/
    features:
      title: Fonctionnalités principales
      description: Tout ce dont vous avez besoin pour une documentation produit professionnelle
      features_list:
      - icon: fas fa-book
        title: Centre de Documentation
        description: Centralisez toute la documentation produit dans une plateforme
          unique et organisée
      - icon: fas fa-code-branch
        title: Contrôle de version
        description: Suivre les modifications et maintenir plusieurs versions de documentation
          à travers les versions de produit
      - icon: fas fa-users
        title: Édition collaborative
        description: Activez la collaboration d'équipe avec l'édition et les commentaires
          en temps réel
      - icon: fas fa-file-export
        title: Exportation multi-format
        description: Exporter la documentation vers PDF, HTML, Markdown et autres
          formats
      - icon: fas fa-sitemap
        title: Réutilisation de contenu
        description: Créez une fois, utilisez partout avec des blocs de contenu modulaires
      - icon: fas fa-language
        title: Localisation
        description: Gérer la documentation en plusieurs langues avec un flux de travail
          de traduction
    carousel:
      title: Documentation Produit en Action
      description: Découvrez comment Docsie transforme la documentation produit
      carousel_slides:
      - image: /assets/solutions/product-docs-case1.jpg
        alt: Software Documentation
        caption: Créer des guides utilisateur logiciels complets
      - image: /assets/solutions/product-docs-case2.jpg
        alt: API Documentation
        caption: Créer une documentation API détaillée
      - image: /assets/solutions/product-docs-case3.jpg
        alt: Release Notes
        caption: Gérer la documentation des versions de produit
    cta:
      text: Voir la démo
      url: /demo/
      style: secondaire
      icon: fas fa-play-circle
    related_auto:
      title: Solutions connexes
      solutions:
      - url: /solutions/technical-documentation/
      - url: /solutions/user-manuals/
      - url: /solutions/knowledge-base/
