- id: training-materials
  category: Solutions
  title: Matériel de formation et documentation
  description: Créez des supports de formation interactifs. Transformez les documents
    de formation traditionnels en expériences d'apprentissage interactives et engageantes
    qui améliorent la rétention des connaissances de 75 %.
  components:
    hero:
      image: /assets/solutions/training-docs-hero.jpg
      title: Plateforme de Documentation de Formation Interactive
      description: Créez des supports de formation engageants qui améliorent les résultats
        d'apprentissage et réduisent le temps de formation de 40 % grâce au contenu
        interactif et au suivi des progrès en temps réel
      cta:
        text: Réserver une démonstration
        url: /demo
    features:
      title: Fonctionnalités principales
      description: Tout ce dont vous avez besoin pour créer du matériel de formation
        moderne
      features_list:
      - icon: fas fa-graduation-cap
        title: Apprentissage Interactif
        description: Créez des formations engageantes avec des quiz, des vidéos et
          des éléments interactifs
      - icon: fas fa-chart-line
        title: Suivi des Progrès
        description: Surveillez la progression des apprenants et les taux de completion
          en temps réel
      - icon: fas fa-mobile-alt
        title: Accès Multi-Appareils
        description: Accédez aux supports de formation sur n'importe quel appareil,
          partout, à tout moment
      - icon: fas fa-language
        title: Prise en charge multilingue
        description: Créer automatiquement du matériel de formation en plusieurs langues
      - icon: fas fa-certificate
        title: Certificats d'achèvement
        description: Générer automatiquement des certificats à la fin de la formation
      - icon: fas fa-sync
        title: Mises à jour du contenu
        description: Diffuser des mises à jour instantanées vers tous les supports
          de formation et notifier les apprenants
    carousel:
      title: Supports de formation en action
      description: Découvrez comment Docsie transforme la documentation de formation
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Créer des supports d'intégration complets pour les employés
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Développer une formation sur la connaissance produit pour les équipes
          de vente
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Créer des programmes de certification avec des évaluations
    related_auto:
      title: Solutions connexes
      solutions:
      - url: /solutions/user-manuals
      - url: /solutions/knowledge-base
      - url: /solutions/sops
    benefits:
      title: Avantages clés
      description: Transformez votre programme de formation
      benefit_list:
      - icon: fas fa-brain
        title: Meilleure Rétention
        description: Améliorez les taux de rétention des connaissances jusqu'à 75
          %
      - icon: fas fa-clock
        title: Formation Accélérée
        description: Réduisez le temps de formation avec du contenu interactif et
          ciblé
      - icon: fas fa-chart-bar
        title: Résultats Mesurables
        description: Suivez l'efficacité de la formation avec des analyses détaillées
      - icon: fas fa-money-bill-wave
        title: Rentable
        description: Réduisez les coûts de formation tout en améliorant les résultats
    cta_section:
      title: Réserver une démonstration
      description: Découvrez comment Docsie peut vous aider à créer une documentation
        de formation engageante qui produit des résultats
      cta:
        text: Réserver une démonstration
        url: /demo
