- id: training-documentation
  category: Solutions
  title: Documentation de formation
  description: Créez des supports de formation efficaces. Élaborez une documentation
    de formation complète qui accélère l'intégration et garantit un transfert de connaissances
    cohérent dans toute votre organisation.
  components:
    hero:
      image: /assets/solutions/training-docs.jpg
      title: Plateforme de Documentation de Formation Professionnelle
      description: Créez du contenu de formation engageant qui réduit le temps d'intégration
        de 40 % et améliore la rétention des connaissances grâce au contenu interactif
      cta:
        text: Réserver une démonstration
        url: /demo
    features:
      title: Fonctionnalités principales
      description: Tout ce dont vous avez besoin pour la documentation de formation
        professionnelle
      features_list:
      - icon: fas fa-graduation-cap
        title: Parcours d'apprentissage
        description: Créer des parcours d'apprentissage et des programmes structurés
      - icon: fas fa-video
        title: Contenu multimédia
        description: Intégrer des vidéos, des quiz et des éléments interactifs
      - icon: fas fa-tasks
        title: Suivi des Progrès
        description: Surveiller les progrès et l'achèvement des apprenants
      - icon: fas fa-certificate
        title: Certifications
        description: Émettre et suivre les certifications de formation
      - icon: fas fa-users
        title: Formation basée sur les rôles
        description: Personnaliser le contenu pour différents rôles
      - icon: fas fa-language
        title: Prise en charge multilingue
        description: Dispenser une formation en plusieurs langues
    carousel:
      title: Documentation de Formation en Action
      description: Découvrez comment Docsie transforme les supports de formation
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Créer une formation complète des employés
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Créer des supports de formation produit
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Gérer les programmes de certification
    related_auto:
      title: Solutions connexes
      solutions:
      - url: /solutions/sops
      - url: /solutions/user-manuals
      - url: /solutions/knowledge-base
    benefits:
      title: Avantages clés
      description: Transformez votre documentation de formation
      benefit_list:
      - icon: fas fa-clock
        title: Intégration plus rapide
        description: Réduisez le temps de formation jusqu'à 40 %
      - icon: fas fa-brain
        title: Meilleure Rétention
        description: Améliorez la rétention des connaissances avec du contenu interactif
      - icon: fas fa-chart-line
        title: Efficacité accrue
        description: Rationaliser la diffusion et la gestion de la formation
      - icon: fas fa-globe
        title: Portée mondiale
        description: Fournir une formation cohérente dans le monde entier
