- id: product-documentation
  category: Solutions
  title: 製品ドキュメント
  description: Docsieで製品専門知識を強化しましょう。ユーザー導入を促進し、サポートコストを削減する包括的な製品ドキュメントを作成・維持する貴社の能力を向上させます。
  components:
    hero:
      image: /assets/solutions/product-docs-hero.jpg
      title: プロフェッショナル製品ドキュメンテーション
      description: 包括的な製品ドキュメントを作成、管理、配信し、ユーザーエクスペリエンスを向上させ、サポート問い合わせを最大65%削減します
      cta:
        text: デモを予約
        url: /demo
    features:
      title: 主要機能
      description: プロフェッショナルな製品ドキュメント作成に必要なすべて
      features_list:
      - icon: fas fa-book
        title: ドキュメントハブ
        description: すべての製品ドキュメントを単一の整理されたプラットフォームに一元化
      - icon: fas fa-code-branch
        title: バージョン管理
        description: 製品リリース全体にわたってドキュメントの変更を追跡し、複数のバージョンを維持する
      - icon: fas fa-users
        title: 共同編集
        description: リアルタイム編集とコメント機能でチーム連携を有効化
      - icon: fas fa-file-export
        title: マルチフォーマットエクスポート
        description: ドキュメントをPDF、HTML、Markdown、その他の形式にエクスポート
      - icon: fas fa-sitemap
        title: コンテンツ再利用
        description: 一度作成すれば、モジュラーコンテンツブロックでどこでも使用可能
      - icon: fas fa-language
        title: ローカライゼーション
        description: 翻訳ワークフローを使用して複数言語でドキュメントを管理
    carousel:
      title: 製品ドキュメントの実践
      description: Docsieが製品ドキュメントをどのように変革するかをご覧ください
      carousel_slides:
      - image: /assets/solutions/product-docs-case1.jpg
        alt: Software Documentation
        caption: 包括的なソフトウェアユーザーガイドを作成する
      - image: /assets/solutions/product-docs-case2.jpg
        alt: API Documentation
        caption: 詳細なAPIドキュメントを構築
      - image: /assets/solutions/product-docs-case3.jpg
        alt: Release Notes
        caption: 製品リリースドキュメントの管理
    cta:
      text: デモを見る
      url: /demo
      style: セカンダリ
      icon: fas fa-play-circle
    related_auto:
      title: 関連ソリューション
      solutions:
      - url: /solutions/technical-documentation
      - url: /solutions/user-manuals
      - url: /solutions/knowledge-base
