- id: training-materials
  category: Solutions
  title: トレーニング資料・ドキュメント
  description: インタラクティブなトレーニング教材を作成。従来のトレーニング文書を魅力的でインタラクティブな学習体験に変換し、知識定着率を75%向上させます。
  components:
    hero:
      image: /assets/solutions/training-docs-hero.jpg
      title: インタラクティブトレーニング文書プラットフォーム
      description: インタラクティブコンテンツとリアルタイム進捗追跡により、学習成果を向上させ、研修時間を40%短縮する魅力的な研修資料を作成
      cta:
        text: デモを予約
        url: /demo/
    features:
      title: 主要機能
      description: モダンなトレーニング教材作成に必要なすべて
      features_list:
      - icon: fas fa-graduation-cap
        title: インタラクティブ学習
        description: クイズ、動画、インタラクティブ要素を使用して魅力的なトレーニングを作成
      - icon: fas fa-chart-line
        title: 進捗追跡
        description: 学習者の進捗状況と完了率をリアルタイムで監視
      - icon: fas fa-mobile-alt
        title: マルチデバイスアクセス
        description: いつでも、どこでも、あらゆるデバイスでトレーニング資料にアクセス
      - icon: fas fa-language
        title: 多言語サポート
        description: 複数言語でのトレーニング資料を自動作成
      - icon: fas fa-certificate
        title: 修了証明書
        description: トレーニング完了時に自動証明書を生成する
      - icon: fas fa-sync
        title: コンテンツ更新
        description: すべてのトレーニング資料に即座に更新をプッシュし、学習者に通知する
    carousel:
      title: 実践的なトレーニング資料
      description: Docsieがトレーニングドキュメントをどのように変革するかをご覧ください
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: 包括的な従業員オンボーディング資料を作成する
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: 営業チーム向け製品知識研修の開発
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: 評価を含む認定プログラムを構築
    related_auto:
      title: 関連ソリューション
      solutions:
      - url: /solutions/user-manuals/
      - url: /solutions/knowledge-base/
      - url: /solutions/sops/
    benefits:
      title: 主要なメリット
      description: トレーニングプログラムを変革する
      benefit_list:
      - icon: fas fa-brain
        title: より良い定着率
        description: 知識定着率を最大75%向上
      - icon: fas fa-clock
        title: 高速トレーニング
        description: 集中的でインタラクティブなコンテンツでトレーニング時間を短縮
      - icon: fas fa-chart-bar
        title: 測定可能な結果
        description: 詳細な分析により研修効果を追跡
      - icon: fas fa-money-bill-wave
        title: コスト効率的
        description: トレーニングコストを削減しながら成果を向上させる
    cta_section:
      title: デモを予約する
      description: Docsieが効果的な結果をもたらす魅力的なトレーニングドキュメントの作成をどのように支援できるかをご覧ください
      cta:
        text: デモを予約
        url: /demo/
