- id: product-documentation
  category: Solutions
  title: Produktová dokumentace
  description: Posílte svou produktovou expertizu s Docsie. Zvyšte schopnost vaší
    společnosti vytvářet a udržovat komplexní produktovou dokumentaci, která podporuje
    adopci uživatelů a snižuje náklady na podporu.
  components:
    hero:
      image: /assets/solutions/product-docs-hero.jpg
      title: Profesionální produktová dokumentace
      description: Vytvářejte, spravujte a poskytujte komplexní produktovou dokumentaci,
        která zlepšuje uživatelskou zkušenost a snižuje počet dotazů na podporu až
        o 65 %
      cta:
        text: Rezervovat demo
        url: /demo/
    features:
      title: Klíčové funkce
      description: Vše, co potřebujete pro profesionální produktovou dokumentaci
      features_list:
      - icon: fas fa-book
        title: Centrum dokumentace
        description: Centralizujte veškerou produktovou dokumentaci v jediné, organizované
          platformě
      - icon: fas fa-code-branch
        title: Správa verzí
        description: Sledujte změny a udržujte více verzí dokumentace napříč vydáními
          produktu
      - icon: fas fa-users
        title: Společné úpravy
        description: Umožněte týmovou spolupráci s úpravami a komentováním v reálném
          čase
      - icon: fas fa-file-export
        title: Export do více formátů
        description: Exportovat dokumentaci do PDF, HTML, Markdown a dalších formátů
      - icon: fas fa-sitemap
        title: Opětovné použití obsahu
        description: '"Vytvořte jednou, používejte všude s modulárními bloky obsahu"'
      - icon: fas fa-language
        title: Lokalizace
        description: Spravujte dokumentaci ve více jazycích pomocí překladového workflow
    carousel:
      title: Produktová dokumentace v praxi
      description: '"Podívejte se, jak Docsie transformuje produktovou dokumentaci"'
      carousel_slides:
      - image: /assets/solutions/product-docs-case1.jpg
        alt: Software Documentation
        caption: Vytvořte komplexní uživatelské příručky pro software
      - image: /assets/solutions/product-docs-case2.jpg
        alt: API Documentation
        caption: Vytvořte podrobnou dokumentaci API
      - image: /assets/solutions/product-docs-case3.jpg
        alt: Release Notes
        caption: Správa dokumentace vydání produktu
    cta:
      text: Zobrazit ukázku
      url: /demo/
      style: sekundární
      icon: fas fa-play-circle
    related_auto:
      title: Související řešení
      solutions:
      - url: /solutions/technical-documentation/
      - url: /solutions/user-manuals/
      - url: /solutions/knowledge-base/
