- id: training-documentation
  category: Solutions
  title: Školicí dokumentace
  description: Vytvářejte efektivní školicí materiály. Sestavujte komplexní školicí
    dokumentaci, která urychluje zapracování a zajišťuje konzistentní přenos znalostí
    napříč vaší organizací.
  components:
    hero:
      image: /assets/solutions/training-docs.jpg
      title: Platforma profesní školicí dokumentace
      description: Vytvářejte poutavé školicí materiály, které zkrátí dobu onboardingu
        o 40 % a zlepší uchování znalostí pomocí interaktivního obsahu
      cta:
        text: Rezervovat demo
        url: /demo/
    features:
      title: Klíčové funkce
      description: Vše, co potřebujete pro profesionální dokumentaci školení
      features_list:
      - icon: fas fa-graduation-cap
        title: Studijní cesty
        description: Vytvářejte strukturované vzdělávací cesty a osnovy
      - icon: fas fa-video
        title: Multimediální obsah
        description: Vložte videa, kvízy a interaktivní prvky
      - icon: fas fa-tasks
        title: Sledování průběhu
        description: Sledovat pokrok a dokončení studentů
      - icon: fas fa-certificate
        title: Certifikace
        description: Vydávat a sledovat certifikace školení
      - icon: fas fa-users
        title: Školení podle rolí
        description: Přizpůsobte obsah pro různé role
      - icon: fas fa-language
        title: Podpora více jazyků
        description: Poskytovat školení ve více jazycích
    carousel:
      title: '"Školicí dokumentace v praxi"'
      description: '"Podívejte se, jak Docsie transformuje školicí materiály"'
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Vytvořit komplexní školení zaměstnanců
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Vytvořit školicí materiály k produktu
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Spravovat certifikační programy
    related_auto:
      title: Související řešení
      solutions:
      - url: /solutions/sops/
      - url: /solutions/user-manuals/
      - url: /solutions/knowledge-base/
    benefits:
      title: Klíčové výhody
      description: Transformujte svou školicí dokumentaci
      benefit_list:
      - icon: fas fa-clock
        title: Rychlejší zapracování
        description: Snižte dobu školení až o 40 %
      - icon: fas fa-brain
        title: Lepší udržení
        description: Zlepšete uchování znalostí pomocí interaktivního obsahu
      - icon: fas fa-chart-line
        title: Zvýšená efektivita
        description: Zefektivněte poskytování a správu školení
      - icon: fas fa-globe
        title: Globální dosah
        description: Poskytujte konzistentní školení po celém světě
