- id: training-materials
  category: Solutions
  title: Školicí materiály a dokumentace
  description: Vytvářejte interaktivní školicí materiály. Transformujte tradiční školicí
    dokumenty na poutavé, interaktivní vzdělávací zážitky, které zlepšují uchování
    znalostí o 75 %.
  components:
    hero:
      image: /assets/solutions/training-docs-hero.jpg
      title: Interaktivní platforma pro školicí dokumentaci
      description: Vytvářejte poutavé školicí materiály, které zvyšují výsledky učení
        a zkracují dobu školení o 40 % díky interaktivnímu obsahu a sledování pokroku
        v reálném čase
      cta:
        text: Rezervovat demo
        url: /demo/
    features:
      title: Klíčové funkce
      description: '"Vše, co potřebujete pro tvorbu moderních školicích materiálů"'
      features_list:
      - icon: fas fa-graduation-cap
        title: Interaktivní učení
        description: Vytvářejte poutavá školení s kvízy, videi a interaktivními prvky
      - icon: fas fa-chart-line
        title: Sledování průběhu
        description: Sledujte pokrok studentů a míru dokončení v reálném čase
      - icon: fas fa-mobile-alt
        title: Přístup z více zařízení
        description: Přístup k výukovým materiálům na jakémkoli zařízení, kdekoli
          a kdykoli
      - icon: fas fa-language
        title: Podpora více jazyků
        description: '"Vytvářejte školicí materiály ve více jazycích automaticky"'
      - icon: fas fa-certificate
        title: Certifikáty o dokončení
        description: Generovat automatické certifikáty po dokončení školení
      - icon: fas fa-sync
        title: Aktualizace obsahu
        description: Okamžitě aktualizujte všechny školicí materiály a upozorněte
          účastníky
    carousel:
      title: '"Školicí materiály v praxi"'
      description: '"Podívejte se, jak Docsie transformuje školicí dokumentaci"'
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Vytvořte komplexní materiály pro zapracování zaměstnanců
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Vytvořit školení produktových znalostí pro obchodní týmy
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Vytvářejte certifikační programy s hodnoceními
    related_auto:
      title: Související řešení
      solutions:
      - url: /solutions/user-manuals/
      - url: /solutions/knowledge-base/
      - url: /solutions/sops/
    benefits:
      title: Klíčové výhody
      description: Transformujte svůj školicí program
      benefit_list:
      - icon: fas fa-brain
        title: Lepší udržení
        description: '"Zlepšete míru uchování znalostí až o 75 %"'
      - icon: fas fa-clock
        title: Rychlejší školení
        description: '"Zkraťte dobu školení pomocí cíleného, interaktivního obsahu"'
      - icon: fas fa-chart-bar
        title: Měřitelné výsledky
        description: Sledujte efektivitu školení pomocí podrobných analýz
      - icon: fas fa-money-bill-wave
        title: Nákladově efektivní
        description: Snižte náklady na školení při zlepšování výsledků
    cta_section:
      title: Rezervovat ukázku
      description: Podívejte se, jak vám Docsie může pomoci vytvořit poutavou školicí
        dokumentaci, která přináší výsledky
      cta:
        text: Rezervovat demo
        url: /demo/
