- id: product-documentation
  category: Solutions
  title: توثيق المنتج
  description: عزز خبرتك في المنتجات مع Docsie. ارتق بقدرة شركتك على إنشاء وصيانة
    وثائق المنتجات الشاملة التي تدفع اعتماد المستخدمين وتقلل تكاليف الدعم.
  components:
    hero:
      image: /assets/solutions/product-docs-hero.jpg
      title: وثائق المنتج المهنية
      description: أنشئ وأدر وقدم وثائق منتجات شاملة تعزز تجربة المستخدم وتقلل استفسارات
        الدعم بنسبة تصل إلى 65%
      cta:
        text: احجز عرضاً توضيحياً
        url: /demo
    features:
      title: الميزات الرئيسية
      description: كل ما تحتاجه لتوثيق المنتجات الاحترافي
      features_list:
      - icon: fas fa-book
        title: مركز الوثائق
        description: '"مركز جميع وثائق المنتج في منصة واحدة ومنظمة"'
      - icon: fas fa-code-branch
        title: التحكم في الإصدارات
        description: تتبع التغييرات والحفاظ على إصدارات متعددة من الوثائق عبر إصدارات
          المنتج
      - icon: fas fa-users
        title: التحرير التعاوني
        description: تمكين التعاون الجماعي مع التحرير والتعليق في الوقت الفعلي
      - icon: fas fa-file-export
        title: تصدير متعدد التنسيقات
        description: تصدير الوثائق إلى تنسيقات PDF وHTML وMarkdown وتنسيقات أخرى
      - icon: fas fa-sitemap
        title: إعادة استخدام المحتوى
        description: أنشئ مرة واحدة، واستخدم في كل مكان مع كتل المحتوى المعيارية
      - icon: fas fa-language
        title: التوطين
        description: إدارة الوثائق بلغات متعددة مع سير عمل الترجمة
    carousel:
      title: '"توثيق المنتج في العمل"'
      description: '"اكتشف كيف تُحوّل Docsie وثائق المنتجات"'
      carousel_slides:
      - image: /assets/solutions/product-docs-case1.jpg
        alt: Software Documentation
        caption: إنشاء أدلة مستخدم شاملة للبرمجيات
      - image: /assets/solutions/product-docs-case2.jpg
        alt: API Documentation
        caption: إنشاء توثيق مفصل لواجهة برمجة التطبيقات
      - image: /assets/solutions/product-docs-case3.jpg
        alt: Release Notes
        caption: إدارة وثائق إصدار المنتج
    cta:
      text: مشاهدة العرض التوضيحي
      url: /demo
      style: ثانوي
      icon: fas fa-play-circle
    related_auto:
      title: الحلول ذات الصلة
      solutions:
      - url: /solutions/technical-documentation
      - url: /solutions/user-manuals
      - url: /solutions/knowledge-base
