- id: product-documentation
  category: Solutions
  title: Documentación del Producto
  description: Potencia tu Experiencia en Productos con Docsie. Eleva la capacidad
    de tu empresa para crear y mantener documentación integral de productos que impulse
    la adopción de usuarios y reduzca los costos de soporte.
  components:
    hero:
      image: /assets/solutions/product-docs-hero.jpg
      title: Documentación Profesional de Productos
      description: Cree, gestione y entregue documentación integral de productos que
        mejore la experiencia del usuario y reduzca las consultas de soporte hasta
        en un 65%
      cta:
        text: Reservar Demo
        url: /demo/
    features:
      title: Características Principales
      description: Todo lo que necesita para documentación profesional de productos
      features_list:
      - icon: fas fa-book
        title: Centro de Documentación
        description: Centralice toda la documentación de productos en una plataforma
          única y organizada
      - icon: fas fa-code-branch
        title: Control de Versiones
        description: Rastree cambios y mantenga múltiples versiones de documentación
          a través de lanzamientos de productos
      - icon: fas fa-users
        title: Edición Colaborativa
        description: Habilite la colaboración en equipo con edición y comentarios
          en tiempo real
      - icon: fas fa-file-export
        title: Exportación Multiformato
        description: Exportar documentación a PDF, HTML, Markdown y otros formatos
      - icon: fas fa-sitemap
        title: Reutilización de Contenido
        description: '"Crea una vez, usa en todas partes con bloques de contenido
          modulares"'
      - icon: fas fa-language
        title: Localización
        description: Gestione documentación en múltiples idiomas con flujo de trabajo
          de traducción
    carousel:
      title: Documentación de Producto en Acción
      description: '"Vea cómo Docsie transforma la documentación de productos"'
      carousel_slides:
      - image: /assets/solutions/product-docs-case1.jpg
        alt: Software Documentation
        caption: Crear guías de usuario de software integrales
      - image: /assets/solutions/product-docs-case2.jpg
        alt: API Documentation
        caption: Crear documentación detallada de API
      - image: /assets/solutions/product-docs-case3.jpg
        alt: Release Notes
        caption: Gestionar documentación de lanzamiento de productos
    cta:
      text: Ver Demostración
      url: /demo/
      style: secundario
      icon: fas fa-play-circle
    related_auto:
      title: Soluciones Relacionadas
      solutions:
      - url: /solutions/technical-documentation/
      - url: /solutions/user-manuals/
      - url: /solutions/knowledge-base/
