- id: training-documentation
  category: Solutions
  title: Documentación de Capacitación
  description: Cree Materiales de Capacitación Efectivos. Desarrolle documentación
    de capacitación integral que acelere la incorporación y garantice una transferencia
    de conocimiento consistente en toda su organización.
  components:
    hero:
      image: /assets/solutions/training-docs.jpg
      title: Plataforma de Documentación de Capacitación Profesional
      description: Cree materiales de capacitación atractivos que reduzcan el tiempo
        de incorporación en un 40% y mejoren la retención del conocimiento con contenido
        interactivo
      cta:
        text: Reservar Demo
        url: /demo
    features:
      title: Características Principales
      description: Todo lo que necesita para documentación de capacitación profesional
      features_list:
      - icon: fas fa-graduation-cap
        title: Rutas de Aprendizaje
        description: Crear rutas de aprendizaje y planes de estudio estructurados
      - icon: fas fa-video
        title: Contenido Multimedia
        description: Insertar videos, cuestionarios y elementos interactivos
      - icon: fas fa-tasks
        title: Seguimiento del Progreso
        description: Monitorear el progreso y finalización del estudiante
      - icon: fas fa-certificate
        title: Certificaciones
        description: Emitir y realizar seguimiento de certificaciones de capacitación
      - icon: fas fa-users
        title: Capacitación Basada en Roles
        description: Personalizar contenido para diferentes roles
      - icon: fas fa-language
        title: Soporte Multiidioma
        description: Impartir capacitación en múltiples idiomas
    carousel:
      title: Documentación de Capacitación en Acción
      description: '"Vea cómo Docsie transforma los materiales de capacitación"'
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Crear capacitación integral de empleados
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Crear materiales de capacitación de productos
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Gestionar programas de certificación
    related_auto:
      title: Soluciones Relacionadas
      solutions:
      - url: /solutions/sops
      - url: /solutions/user-manuals
      - url: /solutions/knowledge-base
    benefits:
      title: Beneficios Clave
      description: Transforme su documentación de capacitación
      benefit_list:
      - icon: fas fa-clock
        title: Incorporación Más Rápida
        description: Reduzca el tiempo de capacitación hasta en un 40%
      - icon: fas fa-brain
        title: Mejor Retención
        description: Mejore la retención del conocimiento con contenido interactivo
      - icon: fas fa-chart-line
        title: Mayor Eficiencia
        description: Optimice la entrega y gestión de capacitación
      - icon: fas fa-globe
        title: Alcance Global
        description: Proporcione capacitación consistente a nivel mundial
