- id: training-materials
  category: Solutions
  title: Materiales de Capacitación y Documentación
  description: Cree Materiales de Capacitación Interactivos. Transforme los documentos
    de capacitación tradicionales en experiencias de aprendizaje interactivas y atractivas
    que mejoran la retención del conocimiento en un 75%.
  components:
    hero:
      image: /assets/solutions/training-docs-hero.jpg
      title: Plataforma de Documentación de Capacitación Interactiva
      description: Cree materiales de capacitación atractivos que mejoren los resultados
        de aprendizaje y reduzcan el tiempo de formación en un 40% con contenido interactivo
        y seguimiento del progreso en tiempo real
      cta:
        text: Reservar Demo
        url: /demo
    features:
      title: Características Principales
      description: Todo lo que necesita para la creación de material de capacitación
        moderno
      features_list:
      - icon: fas fa-graduation-cap
        title: Aprendizaje Interactivo
        description: Cree capacitación atractiva con cuestionarios, videos y elementos
          interactivos
      - icon: fas fa-chart-line
        title: Seguimiento del Progreso
        description: Monitoree el progreso del estudiante y las tasas de finalización
          en tiempo real
      - icon: fas fa-mobile-alt
        title: Acceso Multidispositivo
        description: Acceda a materiales de capacitación en cualquier dispositivo,
          en cualquier lugar, en cualquier momento
      - icon: fas fa-language
        title: Soporte Multiidioma
        description: Cree materiales de capacitación en múltiples idiomas automáticamente
      - icon: fas fa-certificate
        title: Certificados de Finalización
        description: Generar certificados automáticos al completar la capacitación
      - icon: fas fa-sync
        title: Actualizaciones de Contenido
        description: Enviar actualizaciones instantáneas a todos los materiales de
          capacitación y notificar a los estudiantes
    carousel:
      title: Materiales de Capacitación en Acción
      description: '"Vea cómo Docsie transforma la documentación de capacitación"'
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Crear materiales integrales de incorporación de empleados
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Desarrollar capacitación en conocimiento del producto para equipos
          de ventas
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Crear programas de certificación con evaluaciones
    related_auto:
      title: Soluciones Relacionadas
      solutions:
      - url: /solutions/user-manuals
      - url: /solutions/knowledge-base
      - url: /solutions/sops
    benefits:
      title: Beneficios Clave
      description: Transforme su programa de capacitación
      benefit_list:
      - icon: fas fa-brain
        title: Mejor Retención
        description: Mejore las tasas de retención de conocimiento hasta en un 75%
      - icon: fas fa-clock
        title: Entrenamiento Más Rápido
        description: Reduzca el tiempo de capacitación con contenido interactivo y
          enfocado
      - icon: fas fa-chart-bar
        title: Resultados Medibles
        description: Realice un seguimiento de la efectividad del entrenamiento con
          análisis detallados
      - icon: fas fa-money-bill-wave
        title: Rentable
        description: Reduzca los costos de capacitación mientras mejora los resultados
    cta_section:
      title: Solicitar una Demostración
      description: Descubra cómo Docsie puede ayudarle a crear documentación de capacitación
        atractiva que genere resultados
      cta:
        text: Reservar Demo
        url: /demo
