- id: training-documentation
  category: Solutions
  title: Training Documentation Platform - Employee Training Materials
  description: Create effective training docs. Build employee manuals & learning materials.
    Training documentation software for HR and L&D teams.
  components:
    hero:
      image: /assets/solutions/training-docs.jpg
      title: Professional Training Documentation Platform
      description: Create engaging training materials that reduce onboarding time
        by 40% and improve knowledge retention with interactive content
      cta:
        text: Book Demo
        url: /demo/
    features:
      title: Key Features
      description: Everything you need for professional training documentation
      features_list:
      - icon: fas fa-graduation-cap
        title: Learning Paths
        description: Create structured learning paths and curricula
      - icon: fas fa-video
        title: Multimedia Content
        description: Embed videos, quizzes, and interactive elements
      - icon: fas fa-tasks
        title: Progress Tracking
        description: Monitor learner progress and completion
      - icon: fas fa-certificate
        title: Certifications
        description: Issue and track training certifications
      - icon: fas fa-users
        title: Role-Based Training
        description: Customize content for different roles
      - icon: fas fa-language
        title: Multi-language Support
        description: Deliver training in multiple languages
    carousel:
      title: Training Documentation in Action
      description: See how Docsie transforms training materials
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Create comprehensive employee training
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Build product training materials
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Manage certification programs
    related_auto:
      title: Related Solutions
      solutions:
      - url: /solutions/sops/
        title: SOPS Software
        description: Create and manage SOPs for your organization
      - url: /solutions/user-manuals/
        title: User Manuals Software
        description: Create professional user manuals
      - url: /solutions/knowledge-base/
        title: Knowledge Base Software
        description: Create a knowledge base for your organization
        image: /assets/new_home/solutions/solutions-hero.jpg
    benefits:
      title: Key Benefits
      description: Transform your training documentation
      benefit_list:
      - icon: fas fa-clock
        title: Faster Onboarding
        description: Reduce training time by up to 40%
      - icon: fas fa-brain
        title: Better Retention
        description: Improve knowledge retention with interactive content
      - icon: fas fa-chart-line
        title: Increased Efficiency
        description: Streamline training delivery and management
      - icon: fas fa-globe
        title: Global Reach
        description: Deliver consistent training worldwide
