- id: training-materials
  category: Solutions
  title: "Training Materials & Documentation"
  description: "Create Interactive Training Materials. Transform traditional training documents into engaging, interactive learning experiences that improve knowledge retention by 75%."
  components:
    hero:
      image: "/assets/solutions/training-docs-hero.jpg"
      title: "Interactive Training Documentation Platform"
      description: "Create engaging training materials that boost learning outcomes and reduce training time by 40% with interactive content and real-time progress tracking"
      cta:
        text: "Book Demo"
        url: "/demo"
    
    features:
      title: "Key Features"
      description: "Everything you need for modern training material creation"
      features_list:
        - icon: "fas fa-graduation-cap"
          title: "Interactive Learning"
          description: "Create engaging training with quizzes, videos, and interactive elements"
        - icon: "fas fa-chart-line"
          title: "Progress Tracking"
          description: "Monitor learner progress and completion rates in real-time"
        - icon: "fas fa-mobile-alt"
          title: "Multi-Device Access"
          description: "Access training materials on any device, anywhere, anytime"
        - icon: "fas fa-language"
          title: "Multi-Language Support"
          description: "Create training materials in multiple languages automatically"
        - icon: "fas fa-certificate"
          title: "Completion Certificates"
          description: "Generate automatic certificates upon training completion"
        - icon: "fas fa-sync"
          title: "Content Updates"
          description: "Push instant updates to all training materials and notify learners"
    
    carousel:
      title: "Training Materials in Action"
      description: "See how Docsie transforms training documentation"
      carousel_slides:
        - image: "/assets/solutions/training-docs-case1.jpg"
          alt: "Employee Training"
          caption: "Create comprehensive employee onboarding materials"
        - image: "/assets/solutions/training-docs-case2.jpg"
          alt: "Product Training"
          caption: "Develop product knowledge training for sales teams"
        - image: "/assets/solutions/training-docs-case3.jpg"
          alt: "Certification Programs"
          caption: "Build certification programs with assessments"
    
    related_auto:
      title: "Related Solutions"
      solutions:
        - url: "/solutions/user-manuals"
        - url: "/solutions/knowledge-base"
        - url: "/solutions/sops"

    benefits:
      title: "Key Benefits"
      description: "Transform your training program"
      benefit_list:
        - icon: "fas fa-brain"
          title: "Better Retention"
          description: "Improve knowledge retention rates by up to 75%"
        - icon: "fas fa-clock"
          title: "Faster Training"
          description: "Reduce training time with focused, interactive content"
        - icon: "fas fa-chart-bar"
          title: "Measurable Results"
          description: "Track training effectiveness with detailed analytics"
        - icon: "fas fa-money-bill-wave"
          title: "Cost Effective"
          description: "Reduce training costs while improving outcomes"

    cta_section:
      title: "Book a Demo"
      description: "See how Docsie can help you create engaging training documentation that delivers results"
      cta:
        text: "Book Demo"
        url: "/demo"