var contactForm = {
    "heading": "Contact Enterprise Sales",
    "sub_info": "Let's tallk entreprise.",
    "options_text": "I'm interested in...",
    "offer_options": [
        "Priority Support and SLA's",
        "AI powered documentation",
        "Single tenant options",
        "Customer success manager",
        "Private onboarding and training sessions",
        "Private cloud options",
        "Comprehensive project metrics",
        "SAML-based single sign-on (SSO)",
        "Combining multiple projects",
        "Customer OAuth 2 Login",
        "Vendor Security Forms",
        "SLA / ToS modifications",
        "Translations"
    ],
    "desc_place_holder": "Make A Custom Feature Request",
    "contact_btn_text": "Request Information",
    "toggleContactFormText": "Go Back",
    "submitContactFormText": "Submit",
    "firstNameLabel": "First Name",
    "firstNamePH": "Enter Your First Name",
    "lastNameLabel": "Last Name",
    "lastNamePH": "Enter Your Last Name",
    "companyNameLabel": "Company Name",
    "companyNamePH": "Enter Your Company Name",
    "businessEmailLabel": "Business Email",
    "businessEmailPH": "Enter your Business Email",
    "jobTitleLabel": "Job Title",
    "jobTitlePH": "Enter Your Job Title",
    "industryLabel": "Industry",
    "noOfEmployeesLabel": "No. of employees",
    "featureDescriptionLabel": "Description",
    "optionsRequiredMsg": "*Please select atleast one option"
}