- id: training-documentation
  category: Solutions
  title: প্রশিক্ষণ ডকুমেন্টেশন
  description: কার্যকর প্রশিক্ষণ উপকরণ তৈরি করুন। ব্যাপক প্রশিক্ষণ ডকুমেন্টেশন তৈরি
    করুন যা অনবোর্ডিং ত্বরান্বিত করে এবং আপনার প্রতিষ্ঠান জুড়ে সামঞ্জস্যপূর্ণ জ্ঞান
    স্থানান্তর নিশ্চিত করে।
  components:
    hero:
      image: /assets/solutions/training-docs.jpg
      title: পেশাদার প্রশিক্ষণ ডকুমেন্টেশন প্ল্যাটফর্ম
      description: '"ইন্টারঅ্যাক্টিভ কন্টেন্টের মাধ্যমে আকর্ষণীয় প্রশিক্ষণ উপকরণ
        তৈরি করুন যা অনবোর্ডিং সময় ৪০% কমায় এবং জ্ঞান ধারণক্ষমতা উন্নত করে"'
      cta:
        text: ডেমো বুক করুন
        url: /demo/
    features:
      title: মূল বৈশিষ্ট্যসমূহ
      description: পেশাদার প্রশিক্ষণ ডকুমেন্টেশনের জন্য আপনার প্রয়োজনীয় সবকিছু
      features_list:
      - icon: fas fa-graduation-cap
        title: শিক্ষণ পথসমূহ
        description: কাঠামোবদ্ধ শিক্ষার পথ এবং পাঠ্যক্রম তৈরি করুন
      - icon: fas fa-video
        title: মাল্টিমিডিয়া কন্টেন্ট
        description: ভিডিও, কুইজ এবং ইন্টারঅ্যাক্টিভ উপাদান এমবেড করুন
      - icon: fas fa-tasks
        title: অগ্রগতি ট্র্যাকিং
        description: শিক্ষার্থীদের অগ্রগতি এবং সম্পূর্ণতা পর্যবেক্ষণ করুন
      - icon: fas fa-certificate
        title: সার্টিফিকেশন
        description: প্রশিক্ষণ সার্টিফিকেশন ইস্যু এবং ট্র্যাক করুন
      - icon: fas fa-users
        title: ভূমিকা-ভিত্তিক প্রশিক্ষণ
        description: বিভিন্ন ভূমিকার জন্য কন্টেন্ট কাস্টমাইজ করুন
      - icon: fas fa-language
        title: বহুভাষিক সহায়তা
        description: '"একাধিক ভাষায় প্রশিক্ষণ প্রদান করুন"'
    carousel:
      title: '"প্রশিক্ষণ ডকুমেন্টেশন কার্যক্রমে"'
      description: '"দেখুন কিভাবে Docsie প্রশিক্ষণ উপকরণগুলিকে রূপান্তরিত করে"'
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: ব্যাপক কর্মচারী প্রশিক্ষণ তৈরি করুন
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: পণ্য প্রশিক্ষণ উপকরণ তৈরি করুন
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: সার্টিফিকেশন প্রোগ্রাম পরিচালনা করুন
    related_auto:
      title: সংশ্লিষ্ট সমাধানসমূহ
      solutions:
      - url: /solutions/sops/
      - url: /solutions/user-manuals/
      - url: /solutions/knowledge-base/
    benefits:
      title: মূল সুবিধাসমূহ
      description: আপনার প্রশিক্ষণ ডকুমেন্টেশন রূপান্তর করুন
      benefit_list:
      - icon: fas fa-clock
        title: দ্রুততর অনবোর্ডিং
        description: '"প্রশিক্ষণের সময় ৪০% পর্যন্ত হ্রাস করুন"'
      - icon: fas fa-brain
        title: উন্নত ধরে রাখা
        description: ইন্টারঅ্যাক্টিভ কন্টেন্টের মাধ্যমে জ্ঞান ধারণক্ষমতা উন্নত করুন
      - icon: fas fa-chart-line
        title: বর্ধিত দক্ষতা
        description: প্রশিক্ষণ প্রদান এবং ব্যবস্থাপনা সুসংগত করুন
      - icon: fas fa-globe
        title: বিশ্বব্যাপী পৌঁছানো
        description: বিশ্বব্যাপী সামঞ্জস্যপূর্ণ প্রশিক্ষণ প্রদান করুন
