- id: training-materials
  category: Solutions
  title: প্রশিক্ষণ উপকরণ ও ডকুমেন্টেশন
  description: ইন্টারঅ্যাক্টিভ প্রশিক্ষণ উপকরণ তৈরি করুন। ঐতিহ্যবাহী প্রশিক্ষণ নথিগুলিকে
    আকর্ষণীয়, ইন্টারঅ্যাক্টিভ শিক্ষার অভিজ্ঞতায় রূপান্তরিত করুন যা জ্ঞান ধারণক্ষমতা
    ৭৫% উন্নত করে।
  components:
    hero:
      image: /assets/solutions/training-docs-hero.jpg
      title: ইন্টারঅ্যাক্টিভ প্রশিক্ষণ ডকুমেন্টেশন প্ল্যাটফর্ম
      description: '"ইন্টারঅ্যাক্টিভ কন্টেন্ট এবং রিয়েল-টাইম প্রগ্রেস ট্র্যাকিং সহ
        আকর্ষণীয় প্রশিক্ষণ উপকরণ তৈরি করুন যা শেখার ফলাফল বৃদ্ধি করে এবং প্রশিক্ষণের
        সময় ৪০% কমিয়ে দেয়"'
      cta:
        text: ডেমো বুক করুন
        url: /demo
    features:
      title: মূল বৈশিষ্ট্যসমূহ
      description: '"আধুনিক প্রশিক্ষণ উপকরণ তৈরির জন্য আপনার প্রয়োজনীয় সবকিছু"'
      features_list:
      - icon: fas fa-graduation-cap
        title: ইন্টারঅ্যাক্টিভ লার্নিং
        description: '"কুইজ, ভিডিও এবং ইন্টারঅ্যাক্টিভ উপাদান দিয়ে আকর্ষণীয় প্রশিক্ষণ
          তৈরি করুন"'
      - icon: fas fa-chart-line
        title: অগ্রগতি ট্র্যাকিং
        description: '"রিয়েল-টাইমে শিক্ষার্থীদের অগ্রগতি এবং সম্পূর্ণতার হার পর্যবেক্ষণ
          করুন"'
      - icon: fas fa-mobile-alt
        title: মাল্টি-ডিভাইস অ্যাক্সেস
        description: '"যেকোনো ডিভাইসে, যেকোনো স্থানে, যেকোনো সময় প্রশিক্ষণ উপকরণ
          অ্যাক্সেস করুন"'
      - icon: fas fa-language
        title: বহু-ভাষা সহায়তা
        description: '"স্বয়ংক্রিয়ভাবে একাধিক ভাষায় প্রশিক্ষণ উপকরণ তৈরি করুন"'
      - icon: fas fa-certificate
        title: সমাপনী সনদপত্র
        description: প্রশিক্ষণ সম্পন্ন হওয়ার পর স্বয়ংক্রিয় সার্টিফিকেট তৈরি করুন
      - icon: fas fa-sync
        title: কন্টেন্ট আপডেট
        description: সকল প্রশিক্ষণ উপকরণে তাৎক্ষণিক আপডেট পুশ করুন এবং শিক্ষার্থীদের
          অবহিত করুন
    carousel:
      title: '"প্রশিক্ষণ উপকরণ কার্যক্রমে"'
      description: '"দেখুন কিভাবে Docsie প্রশিক্ষণ ডকুমেন্টেশনকে রূপান্তরিত করে"'
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: ব্যাপক কর্মচারী অনবোর্ডিং উপকরণ তৈরি করুন
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: বিক্রয় দলের জন্য পণ্য জ্ঞান প্রশিক্ষণ উন্নয়ন করুন
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: মূল্যায়নসহ সার্টিফিকেশন প্রোগ্রাম তৈরি করুন
    related_auto:
      title: সংশ্লিষ্ট সমাধানসমূহ
      solutions:
      - url: /solutions/user-manuals
      - url: /solutions/knowledge-base
      - url: /solutions/sops
    benefits:
      title: মূল সুবিধাসমূহ
      description: আপনার প্রশিক্ষণ কর্মসূচি রূপান্তর করুন
      benefit_list:
      - icon: fas fa-brain
        title: উন্নত ধরে রাখা
        description: '"জ্ঞান ধারণের হার ৭৫% পর্যন্ত উন্নত করুন"'
      - icon: fas fa-clock
        title: দ্রুততর প্রশিক্ষণ
        description: '"ফোকাসড, ইন্টারঅ্যাক্টিভ কন্টেন্টের মাধ্যমে প্রশিক্ষণের সময়
          হ্রাস করুন"'
      - icon: fas fa-chart-bar
        title: পরিমাপযোগ্য ফলাফল
        description: বিস্তারিত বিশ্লেষণের মাধ্যমে প্রশিক্ষণের কার্যকারিতা ট্র্যাক
          করুন
      - icon: fas fa-money-bill-wave
        title: ব্যয়সাশ্রয়ী
        description: '"প্রশিক্ষণ খরচ কমান এবং ফলাফল উন্নত করুন"'
    cta_section:
      title: ডেমো বুক করুন
      description: '"দেখুন কিভাবে Docsie আপনাকে আকর্ষণীয় প্রশিক্ষণ ডকুমেন্টেশন তৈরি
        করতে সাহায্য করতে পারে যা ফলাফল প্রদান করে"'
      cta:
        text: ডেমো বুক করুন
        url: /demo
