- id: training-materials
  category: Solutions
  title: Schulungsmaterialien & Dokumentation
  description: Erstellen Sie interaktive Schulungsmaterialien. Verwandeln Sie herkömmliche
    Schulungsdokumente in ansprechende, interaktive Lernerfahrungen, die die Wissensbewahrung
    um 75% verbessern.
  components:
    hero:
      image: /assets/solutions/training-docs-hero.jpg
      title: Interaktive Schulungsdokumentationsplattform
      description: Erstellen Sie ansprechende Schulungsmaterialien, die Lernergebnisse
        verbessern und die Schulungszeit um 40% reduzieren – mit interaktiven Inhalten
        und Echtzeit-Fortschrittsverfolgung
      cta:
        text: Demo buchen
        url: /demo
    features:
      title: Hauptfunktionen
      description: '"Alles, was Sie für die Erstellung moderner Schulungsunterlagen
        benötigen"'
      features_list:
      - icon: fas fa-graduation-cap
        title: Interaktives Lernen
        description: Erstellen Sie ansprechende Schulungen mit Quizzes, Videos und
          interaktiven Elementen
      - icon: fas fa-chart-line
        title: Fortschrittsverfolgung
        description: Lernfortschritt und Abschlussquoten in Echtzeit überwachen
      - icon: fas fa-mobile-alt
        title: Zugriff von mehreren Geräten
        description: Greifen Sie jederzeit und überall von jedem Gerät auf Schulungsmaterialien
          zu
      - icon: fas fa-language
        title: Mehrsprachige Unterstützung
        description: Schulungsmaterialien automatisch in mehreren Sprachen erstellen
      - icon: fas fa-certificate
        title: Abschlusszertifikate
        description: Automatische Zertifikate bei Schulungsabschluss generieren
      - icon: fas fa-sync
        title: Inhaltsaktualisierungen
        description: Sofortige Updates an alle Schulungsmaterialien übertragen und
          Lernende benachrichtigen
    carousel:
      title: Schulungsmaterialien in der Praxis
      description: '"Sehen Sie, wie Docsie die Schulungsdokumentation transformiert"'
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Umfassende Mitarbeiter-Onboarding-Materialien erstellen
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Produktwissen-Schulungen für Vertriebsteams entwickeln
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Zertifizierungsprogramme mit Bewertungen erstellen
    related_auto:
      title: Verwandte Lösungen
      solutions:
      - url: /solutions/user-manuals
      - url: /solutions/knowledge-base
      - url: /solutions/sops
    benefits:
      title: Hauptvorteile
      description: Transformieren Sie Ihr Schulungsprogramm
      benefit_list:
      - icon: fas fa-brain
        title: Bessere Kundenbindung
        description: Verbessern Sie die Wissensretentionsrate um bis zu 75%
      - icon: fas fa-clock
        title: Schnelleres Training
        description: Reduzieren Sie die Schulungszeit mit fokussierten, interaktiven
          Inhalten
      - icon: fas fa-chart-bar
        title: Messbare Ergebnisse
        description: Verfolgen Sie die Schulungseffektivität mit detaillierten Analysen
      - icon: fas fa-money-bill-wave
        title: Kosteneffektiv
        description: Trainingskosten reduzieren und gleichzeitig Ergebnisse verbessern
    cta_section:
      title: Demo buchen
      description: Erfahren Sie, wie Docsie Ihnen dabei helfen kann, ansprechende
        Schulungsunterlagen zu erstellen, die Ergebnisse liefern
      cta:
        text: Demo buchen
        url: /demo
