- id: training-documentation
  category: Solutions
  title: Schulungsdokumentation
  description: Erstellen Sie effektive Schulungsunterlagen. Entwickeln Sie umfassende
    Schulungsdokumentationen, die das Onboarding beschleunigen und einen konsistenten
    Wissenstransfer in Ihrem Unternehmen gewährleisten.
  components:
    hero:
      image: /assets/solutions/training-docs.jpg
      title: Professionelle Schulungsdokumentationsplattform
      description: Erstellen Sie ansprechende Schulungsmaterialien, die die Einarbeitungszeit
        um 40% reduzieren und die Wissensbewahrung durch interaktive Inhalte verbessern
      cta:
        text: Demo buchen
        url: /demo/
    features:
      title: Hauptfunktionen
      description: Alles, was Sie für professionelle Schulungsunterlagen benötigen
      features_list:
      - icon: fas fa-graduation-cap
        title: Lernpfade
        description: Strukturierte Lernpfade und Curricula erstellen
      - icon: fas fa-video
        title: Multimedia-Inhalte
        description: Videos, Quiz und interaktive Elemente einbetten
      - icon: fas fa-tasks
        title: Fortschrittsverfolgung
        description: Lernfortschritt und Abschluss überwachen
      - icon: fas fa-certificate
        title: Zertifizierungen
        description: Schulungszertifikate ausstellen und verfolgen
      - icon: fas fa-users
        title: Rollenbasierte Schulung
        description: Inhalte für verschiedene Rollen anpassen
      - icon: fas fa-language
        title: Mehrsprachige Unterstützung
        description: Schulungen in mehreren Sprachen bereitstellen
    carousel:
      title: Schulungsdokumentation in der Praxis
      description: '"Sehen Sie, wie Docsie Schulungsunterlagen transformiert"'
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Umfassende Mitarbeiterschulung erstellen
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Produktschulungsunterlagen erstellen
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Zertifizierungsprogramme verwalten
    related_auto:
      title: Verwandte Lösungen
      solutions:
      - url: /solutions/sops/
      - url: /solutions/user-manuals/
      - url: /solutions/knowledge-base/
    benefits:
      title: Hauptvorteile
      description: Transformieren Sie Ihre Schulungsunterlagen
      benefit_list:
      - icon: fas fa-clock
        title: Schnelleres Onboarding
        description: Reduzieren Sie die Schulungszeit um bis zu 40%
      - icon: fas fa-brain
        title: Bessere Kundenbindung
        description: Verbessern Sie die Wissensbewahrung mit interaktiven Inhalten
      - icon: fas fa-chart-line
        title: Erhöhte Effizienz
        description: Optimierung der Schulungsbereitstellung und -verwaltung
      - icon: fas fa-globe
        title: Globale Reichweite
        description: Konsistente Schulungen weltweit bereitstellen
