- id: product-documentation
  category: Solutions
  title: Documentação do Produto
  description: Potencialize Sua Expertise em Produtos com o Docsie. Eleve a capacidade
    da sua empresa de criar e manter documentação abrangente de produtos que impulsiona
    a adoção pelos usuários e reduz os custos de suporte.
  components:
    hero:
      image: /assets/solutions/product-docs-hero.jpg
      title: Documentação Profissional de Produto
      description: Crie, gerencie e entregue documentação abrangente de produtos que
        aprimora a experiência do usuário e reduz consultas de suporte em até 65%
      cta:
        text: Agendar Demonstração
        url: /demo/
    features:
      title: Principais Funcionalidades
      description: Tudo o que você precisa para documentação profissional de produtos
      features_list:
      - icon: fas fa-book
        title: Central de Documentação
        description: Centralize toda a documentação do produto em uma única plataforma
          organizada
      - icon: fas fa-code-branch
        title: Controle de Versão
        description: Rastreie alterações e mantenha múltiplas versões da documentação
          em diferentes lançamentos de produtos
      - icon: fas fa-users
        title: Edição Colaborativa
        description: Habilite a colaboração em equipe com edição e comentários em
          tempo real
      - icon: fas fa-file-export
        title: Exportação Multi-formato
        description: Exportar documentação para PDF, HTML, Markdown e outros formatos
      - icon: fas fa-sitemap
        title: Reutilização de Conteúdo
        description: '"Crie uma vez, use em qualquer lugar com blocos de conteúdo
          modulares"'
      - icon: fas fa-language
        title: Localização
        description: Gerencie documentação em vários idiomas com fluxo de trabalho
          de tradução
    carousel:
      title: Documentação do Produto em Ação
      description: '"Veja como o Docsie transforma a documentação de produtos"'
      carousel_slides:
      - image: /assets/solutions/product-docs-case1.jpg
        alt: Software Documentation
        caption: Criar guias de usuário de software abrangentes
      - image: /assets/solutions/product-docs-case2.jpg
        alt: API Documentation
        caption: Criar documentação detalhada de API
      - image: /assets/solutions/product-docs-case3.jpg
        alt: Release Notes
        caption: Gerenciar documentação de lançamento de produto
    cta:
      text: Ver Demonstração
      url: /demo/
      style: secundário
      icon: fas fa-play-circle
    related_auto:
      title: Soluções Relacionadas
      solutions:
      - url: /solutions/technical-documentation/
      - url: /solutions/user-manuals/
      - url: /solutions/knowledge-base/
