- id: training-documentation
  category: Solutions
  title: Documentação de Treinamento
  description: Crie Materiais de Treinamento Eficazes. Desenvolva documentação de
    treinamento abrangente que acelera a integração e garante transferência consistente
    de conhecimento em toda a sua organização.
  components:
    hero:
      image: /assets/solutions/training-docs.jpg
      title: Plataforma de Documentação de Treinamento Profissional
      description: Crie materiais de treinamento envolventes que reduzem o tempo de
        integração em 40% e melhoram a retenção de conhecimento com conteúdo interativo
      cta:
        text: Agendar Demonstração
        url: /demo
    features:
      title: Principais Funcionalidades
      description: Tudo o que você precisa para documentação de treinamento profissional
      features_list:
      - icon: fas fa-graduation-cap
        title: Trilhas de Aprendizagem
        description: Criar caminhos de aprendizagem e currículos estruturados
      - icon: fas fa-video
        title: Conteúdo Multimídia
        description: Incorporar vídeos, questionários e elementos interativos
      - icon: fas fa-tasks
        title: Acompanhamento de Progresso
        description: Monitorar o progresso e a conclusão do aluno
      - icon: fas fa-certificate
        title: Certificações
        description: Emitir e rastrear certificações de treinamento
      - icon: fas fa-users
        title: Treinamento Baseado em Funções
        description: Personalizar conteúdo para diferentes funções
      - icon: fas fa-language
        title: Suporte a Múltiplos Idiomas
        description: Fornecer treinamento em vários idiomas
    carousel:
      title: '"Documentação de Treinamento em Ação"'
      description: '"Veja como o Docsie transforma materiais de treinamento"'
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Criar treinamento abrangente de funcionários
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Criar materiais de treinamento de produto
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Gerenciar programas de certificação
    related_auto:
      title: Soluções Relacionadas
      solutions:
      - url: /solutions/sops
      - url: /solutions/user-manuals
      - url: /solutions/knowledge-base
    benefits:
      title: Principais Benefícios
      description: Transforme sua documentação de treinamento
      benefit_list:
      - icon: fas fa-clock
        title: '"Integração Mais Rápida"'
        description: Reduza o tempo de treinamento em até 40%
      - icon: fas fa-brain
        title: Melhor Retenção
        description: Melhore a retenção de conhecimento com conteúdo interativo
      - icon: fas fa-chart-line
        title: Eficiência Aumentada
        description: '"Otimize a entrega e o gerenciamento de treinamentos"'
      - icon: fas fa-globe
        title: Alcance Global
        description: Forneça treinamento consistente mundialmente
