- id: training-materials
  category: Solutions
  title: Materiais de Treinamento e Documentação
  description: Crie Materiais de Treinamento Interativos. Transforme documentos de
    treinamento tradicionais em experiências de aprendizado envolventes e interativas
    que melhoram a retenção de conhecimento em 75%.
  components:
    hero:
      image: /assets/solutions/training-docs-hero.jpg
      title: Plataforma de Documentação de Treinamento Interativo
      description: Crie materiais de treinamento envolventes que aumentam os resultados
        de aprendizagem e reduzem o tempo de treinamento em 40% com conteúdo interativo
        e acompanhamento de progresso em tempo real
      cta:
        text: Agendar Demonstração
        url: /demo/
    features:
      title: Principais Funcionalidades
      description: '"Tudo o que você precisa para criação de material de treinamento
        moderno"'
      features_list:
      - icon: fas fa-graduation-cap
        title: Aprendizagem Interativa
        description: Crie treinamentos envolventes com questionários, vídeos e elementos
          interativos
      - icon: fas fa-chart-line
        title: Acompanhamento de Progresso
        description: Monitore o progresso do aluno e as taxas de conclusão em tempo
          real
      - icon: fas fa-mobile-alt
        title: Acesso Multi-Dispositivo
        description: Acesse materiais de treinamento em qualquer dispositivo, em qualquer
          lugar, a qualquer momento
      - icon: fas fa-language
        title: Suporte a Múltiplos Idiomas
        description: Crie materiais de treinamento em vários idiomas automaticamente
      - icon: fas fa-certificate
        title: Certificados de Conclusão
        description: Gerar certificados automáticos após a conclusão do treinamento
      - icon: fas fa-sync
        title: Atualizações de Conteúdo
        description: Envie atualizações instantâneas para todos os materiais de treinamento
          e notifique os alunos
    carousel:
      title: '"Materiais de Treinamento em Ação"'
      description: '"Veja como o Docsie transforma a documentação de treinamento"'
      carousel_slides:
      - image: /assets/solutions/training-docs-case1.jpg
        alt: Employee Training
        caption: Criar materiais abrangentes de integração de funcionários
      - image: /assets/solutions/training-docs-case2.jpg
        alt: Product Training
        caption: Desenvolver treinamento de conhecimento do produto para equipes de
          vendas
      - image: /assets/solutions/training-docs-case3.jpg
        alt: Certification Programs
        caption: Construa programas de certificação com avaliações
    related_auto:
      title: Soluções Relacionadas
      solutions:
      - url: /solutions/user-manuals/
      - url: /solutions/knowledge-base/
      - url: /solutions/sops/
    benefits:
      title: Principais Benefícios
      description: Transforme seu programa de treinamento
      benefit_list:
      - icon: fas fa-brain
        title: Melhor Retenção
        description: '"Melhore as taxas de retenção de conhecimento em até 75%"'
      - icon: fas fa-clock
        title: Treinamento Mais Rápido
        description: '"Reduza o tempo de treinamento com conteúdo focado e interativo"'
      - icon: fas fa-chart-bar
        title: Resultados Mensuráveis
        description: Acompanhe a eficácia do treinamento com análises detalhadas
      - icon: fas fa-money-bill-wave
        title: Custo-Efetivo
        description: Reduza os custos de treinamento enquanto melhora os resultados
    cta_section:
      title: Agendar uma Demonstração
      description: Veja como o Docsie pode ajudá-lo a criar documentação de treinamento
        envolvente que entrega resultados
      cta:
        text: Agendar Demonstração
        url: /demo/
