name: Deploy to GitHub Pages (Optimized)

on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        run: |
          echo "=== Initial disk space ==="
          df -h
          
          echo "=== Removing unnecessary software ==="
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/share/swift
          
          echo "=== Cleaning package manager cache ==="
          sudo apt-get clean
          sudo apt-get autoremove -y
          
          echo "=== Final disk space ==="
          df -h
          
      - name: Checkout repository (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Remove non-essential files
        run: |
          # Remove all language-specific asset folders (they're duplicates)
          find . -type d -path "*/assets" -not -path "./assets" -exec rm -rf {} + 2>/dev/null || true
          
          # Remove source and build files
          rm -rf src/
          rm -rf locale/
          rm -rf venv/
          rm -rf node_modules/
          rm -rf .git/
          find . -name "*.py" -delete
          find . -name "*.pyc" -delete
          find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
          find . -name "*.sh" -delete
          find . -name "*.md" -not -name "README.md" -delete
          find . -name "*.txt" -not -name "CNAME" -delete
          find . -name "*.yaml" -delete
          find . -name "*.yml" -not -path "./.github/*" -delete
          find . -name ".DS_Store" -delete
          
          echo "Repository size after cleanup:"
          du -sh .
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4